#!/usr/bin/env escript
%% -*- erlang -*-
%%! -noshell

%% @doc Takes the coverdata files generated by the cover module and creates
%% reports out of them. Each module analysed by the system generates an
%% X_coverage.txt file.
main(_) ->
    [cover:import(File) || File <- filelib:wildcard("*.coverdata")],
    lists:foreach(
        fun(Module) ->
            cover:analyse_to_file(
                Module, atom_to_list(Mod) ++ "_coverage.txt", []
            )
        end,
        cover:imported_modules()
    ).

